const message = [
  {
    id: 1,
    name: 'Maicon Souza',
    postName: 'maicon08_oficial',
    image: require('../images/maicon_01.png'),
    postImage: require('../images/maicon_02.png'),
    like: 160,
    comment: 'ver todos os 4 comentários',
    explanation: 'Obrigado @andersonaguia e @romariofaria pelo convite, estrutura top do @tafc_futevolei , muito feliz em ter participado desse grande evento e ainda mais por ter chego na final, e não poderia deixar de agradecer meu parceiro @brunoreislino valeu pelos jogos e parceria Tmj !!',
    time: 'Há 2 horas',
    timeStory: '53d',
    islike: false,
  },

  {
    id: 2,
    name: 'Fabio',
    postName: 'molequezagueiro',
    image: require('../images/mlk_01.png'),
    postImage: require('../images/mlk_02.png'),
    like: 360,
    comment: 'ver todos os 4 comentários',
    explanation: 'Rasgada de pingo nível 2',
    time: 'Há 2 horas',
    timeStory: '53d',
    islike: false,
  },
  {
    id: 3,
    name: 'Fabricio Brisa',
    postName: 'brisaftv',
    image: require('../images/brisa_01.png'),
    postImage: require('../images/brisa_02.png'),
    like: 120,
    comment: 'ver todos os 4 comentários',
    explanation: 'CAMPEÃO DO DESAFIO',
    time: 'Há 3 horas',
    timeStory: '2s',
    islike: false,
  },
  {
    id: 4,
    name: 'CT RPai',
    postName: 'ct_rpai',
    image: require('../images/rpai_01.png'),
    postImage: require('../images/rpai_02.png'),
    like: 160,
    comment: 'ver todos os 8 comentários',
    explanation: 'O Maracanã do Rio de Janeiro',
    time: 'Há 5 horas',
    timeStory: '3s',
    islike: false,
  },
  {
    id: 5,
    name: 'Bruno Barros',
    postName: 'brunobarros19',
    image: require('../images/bbarros_01.png'),
    postImage: require('../images/bbarros_02.png'),
    like: 220,
    comment: 'ver todos os 110 comentários',
    explanation: 'Tudo passa',
    time: 'Há 8 horas',
    timeStory: '6s',
    islike: false,
  },
  {
    id: 6,
    name: 'Bruno Vasconcelos',
    postName: 'bruninhofutevolei',
    image: require('../images/bftv_01.png'),
    postImage: require('../images/bftv_02.png'),
    like: 150,
    comment: 'ver todos os 25 comentários',
    explanation: 'Aquela balançada',
    time: '1 dia',
    timeStory: '24s',
    islike: false,
  },
];
export default message;
